# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: ./Generate.bat
  displayName: 'Generate build files'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
