trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    git submodule init
    git submodule update
  displayName: 'Get submodules'

- script: ./Generate.bat
  displayName: 'Generate build files'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: 'x64'